<a href="https://colab.research.google.com/github/bhavyajaiswal27/SummerDB/blob/master/Fertilizer_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!mkdir -p ~/.kaggle
!cp '/content/kaggle (1).json' ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

In [6]:
!kaggle competitions download -c playground-series-s5e6

Downloading playground-series-s5e6.zip to /content
  0% 0.00/11.7M [00:00<?, ?B/s]
100% 11.7M/11.7M [00:00<00:00, 886MB/s]

In [7]:
!unzip playground-series-s5e6.zip -d playground-series-s5e6

Archive:  playground-series-s5e6.zip
  inflating: playground-series-s5e6/sample_submission.csv
  inflating: playground-series-s5e6/test.csv
  inflating: playground-series-s5e6/train.csv

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv('/content/playground-series-s5e6/train.csv')
test = pd.read_csv('/content/playground-series-s5e6/test.csv')

   id  Temparature  Humidity  Moisture Soil Type  Crop Type  Nitrogen  \
0   0           37        70        36    Clayey  Sugarcane        36
1   1           27        69        65     Sandy    Millets        30
2   2           29        63        32     Sandy    Millets        24
3   3           35        62        54     Sandy     Barley        39
4   4           35        58        43       Red      Paddy        37

   Potassium  Phosphorous Fertilizer Name
0          4            5           28-28
1          6           18           28-28
2         12           16        17-17-17
3         12            4        10-26-26
4          2           16             DAP
       id  Temparature  Humidity  Moisture Soil Type    Crop Type  Nitrogen  \
0  750000           31        70        52     Sandy        Wheat        34
1  750001           27        62        45       Red    Sugarcane        30
2  750002           28        72        28    Clayey  Ground Nuts        14
3  750003           37        53        57     Black  Ground Nuts        18
4  750004           31        55        32       Red       Pulses        13

   Potassium  Phosphorous
0         11           24
1         14           15
2         15            4
3         17           36
4         19           14

In [3]:
train.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,0,37,70,36,Clayey,Sugarcane,36,4,5,28-28
1,1,27,69,65,Sandy,Millets,30,6,18,28-28
2,2,29,63,32,Sandy,Millets,24,12,16,17-17-17
3,3,35,62,54,Sandy,Barley,39,12,4,10-26-26
4,4,35,58,43,Red,Paddy,37,2,16,DAP

In [2]:
test.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,750000,31,70,52,Sandy,Wheat,34,11,24
1,750001,27,62,45,Red,Sugarcane,30,14,15
2,750002,28,72,28,Clayey,Ground Nuts,14,15,4
3,750003,37,53,57,Black,Ground Nuts,18,17,36
4,750004,31,55,32,Red,Pulses,13,19,14

In [6]:
train.columns

Index(['id', 'Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [5]:
from sklearn.preprocessing import LabelEncoder
ll = LabelEncoder()
mm = LabelEncoder()
train['Soil Type'] = ll.fit_transform(train['Soil Type'])
train['Crop Type'] = ll.fit_transform(train['Crop Type'])
train['Fertilizer Name'] = mm.fit_transform(train['Fertilizer Name'])
test['Soil Type'] = ll.fit_transform(test['Soil Type'])
test['Crop Type'] = ll.fit_transform(test['Crop Type'])

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
col = ['Temparature', 'Humidity', 'Moisture', 'Nitrogen', 'Potassium', 'Phosphorous']
train[col] = scaler.fit_transform(train[col])
test[col] = scaler.fit_transform(test[col])

In [8]:
train.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,0,0.923077,0.909091,0.275,1,8,0.842105,0.210526,0.119048,4
1,1,0.153846,0.863636,1.000,4,4,0.684211,0.315789,0.428571,4
2,2,0.307692,0.590909,0.175,4,4,0.526316,0.631579,0.380952,2
3,3,0.769231,0.545455,0.725,4,0,0.921053,0.631579,0.095238,0
4,4,0.769231,0.363636,0.450,3,6,0.868421,0.105263,0.380952,5

In [9]:
test.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,750000,0.461538,0.909091,0.675,4,10,0.789474,0.578947,0.571429
1,750001,0.153846,0.545455,0.500,3,8,0.684211,0.736842,0.357143
2,750002,0.230769,1.000000,0.075,1,2,0.263158,0.789474,0.095238
3,750003,0.923077,0.136364,0.800,0,2,0.368421,0.894737,0.857143
4,750004,0.461538,0.227273,0.175,3,7,0.236842,1.000000,0.333333

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train.drop(['id', 'Fertilizer Name'], axis=1), train['Fertilizer Name'])

LinearRegression()

In [14]:
ypred = model.predict(test.drop(['id'], axis=1))

In [20]:
print(ypred.max)

<built-in method max of numpy.ndarray object at 0x7fc64223b8d0>

In [12]:
ypred = mm.inverse_transform(ypred.astype(int))

In [13]:
submit = pd.DataFrame({'id': test['id'], 'Fertilizer Name': ypred})
submit.to_csv('submission.csv', index=False)

# Rejected Part

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/playground-series-s5e6/train.csv')
df.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,0,37,70,36,Clayey,Sugarcane,36,4,5,28-28
1,1,27,69,65,Sandy,Millets,30,6,18,28-28
2,2,29,63,32,Sandy,Millets,24,12,16,17-17-17
3,3,35,62,54,Sandy,Barley,39,12,4,10-26-26
4,4,35,58,43,Red,Paddy,37,2,16,DAP

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               750000 non-null  int64
 1   Temparature      750000 non-null  int64
 2   Humidity         750000 non-null  int64
 3   Moisture         750000 non-null  int64
 4   Soil Type        750000 non-null  object
 5   Crop Type        750000 non-null  object
 6   Nitrogen         750000 non-null  int64
 7   Potassium        750000 non-null  int64
 8   Phosphorous      750000 non-null  int64
 9   Fertilizer Name  750000 non-null  object
dtypes: int64(7), object(3)
memory usage: 57.2+ MB

In [10]:
df.shape

(750000, 10)

In [11]:
df.isnull().any()

id                 False
Temparature        False
Humidity           False
Moisture           False
Soil Type          False
Crop Type          False
Nitrogen           False
Potassium          False
Phosphorous        False
Fertilizer Name    False
dtype: bool

In [12]:
df.columns

Index(['id', 'Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [13]:
df['Fertilizer Name'].unique()

array(['28-28', '17-17-17', '10-26-26', 'DAP', '20-20', '14-35-14',
       'Urea'], dtype=object)

In [14]:
df.describe()

,id,Temparature,Humidity,Moisture,Nitrogen,Potassium,Phosphorous
count,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000
mean,374999.500000,31.503565,61.038912,45.184147,23.093808,9.478296,21.073227
std,216506.495284,4.025574,6.647695,11.794594,11.216125,5.765622,12.346831
min,0.000000,25.000000,50.000000,25.000000,4.000000,0.000000,0.000000
25%,187499.750000,28.000000,55.000000,35.000000,13.000000,4.000000,10.000000
50%,374999.500000,32.000000,61.000000,45.000000,23.000000,9.000000,21.000000
75%,562499.250000,35.000000,67.000000,55.000000,33.000000,14.000000,32.000000
max,749999.000000,38.000000,72.000000,65.000000,42.000000,19.000000,42.000000

In [48]:
coll = ['Soil Type', 'Crop Type', 'Fertilizer Name']
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in coll:
  df[i] = le.fit_transform(df[i])

In [33]:
col = ['Temparature', 'Humidity', 'Moisture', 'Nitrogen', 'Potassium', 'Phosphorous']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[col] = scaler.fit_transform(df[col])

In [34]:
df.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,0,0.923077,0.909091,0.275,1,8,0.842105,0.210526,0.119048,4
1,1,0.153846,0.863636,1.000,4,4,0.684211,0.315789,0.428571,4
2,2,0.307692,0.590909,0.175,4,4,0.526316,0.631579,0.380952,2
3,3,0.769231,0.545455,0.725,4,0,0.921053,0.631579,0.095238,0
4,4,0.769231,0.363636,0.450,3,6,0.868421,0.105263,0.380952,5

In [35]:
df['Crop Type'].unique()

array([ 8,  4,  0,  6,  7,  9,  2,  3,  1, 10,  5])

In [45]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(df.drop(['id', 'Fertilizer Name'], axis=1), df['Fertilizer Name'])

LinearRegression()

In [37]:
test = pd.read_csv('/content/playground-series-s5e6/test.csv')
test.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,750000,31,70,52,Sandy,Wheat,34,11,24
1,750001,27,62,45,Red,Sugarcane,30,14,15
2,750002,28,72,28,Clayey,Ground Nuts,14,15,4
3,750003,37,53,57,Black,Ground Nuts,18,17,36
4,750004,31,55,32,Red,Pulses,13,19,14

In [38]:
test.isnull().any()

id             False
Temparature    False
Humidity       False
Moisture       False
Soil Type      False
Crop Type      False
Nitrogen       False
Potassium      False
Phosphorous    False
dtype: bool

In [49]:
coll = ['Soil Type', 'Crop Type']
for i in coll:
  test[i] = le.fit_transform(test[i])

In [50]:
col = ['Temparature', 'Humidity', 'Moisture', 'Nitrogen', 'Potassium', 'Phosphorous']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
test[col] = scaler.fit_transform(test[col])

In [51]:
test.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,750000,0.461538,0.909091,0.675,4,10,0.789474,0.578947,0.571429
1,750001,0.153846,0.545455,0.500,3,8,0.684211,0.736842,0.357143
2,750002,0.230769,1.000000,0.075,1,2,0.263158,0.789474,0.095238
3,750003,0.923077,0.136364,0.800,0,2,0.368421,0.894737,0.857143
4,750004,0.461538,0.227273,0.175,3,7,0.236842,1.000000,0.333333

In [42]:
test.columns

Index(['id', 'Temparature', 'Humidity', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous'],
      dtype='object')

In [52]:
y_pred = model.predict(test.drop(['id'], axis=1))

In [55]:
y_pred = le.inverse_transform(y_pred.astype(int))

In [56]:
submit = pd.DataFrame({'id': test['id'], 'Fertilizer Name': y_pred})
submit.to_csv('submission.csv', index=False)

In [ ]:
!kaggle competitions submit -c <playground-series-s5e6> -f submission.csv -m "First submission"